### ISSUE TITLE
Problem regarding the evaluation codes of the GSM8K - `eval_gsm8k.py`

### ISSUE THREAD

**Issue by SuperBruceJia** [meta-math/MetaMath#11]
In [line 87](https://github.com/meta-math/MetaMath/blob/main/eval_gsm8k.py#L87), batch data of the prompts is implemented. However, in [line 95](https://github.com/meta-math/MetaMath/blob/main/eval_gsm8k.py#L95), the answer labels are not used as batches. If you output
```python
for idx, (prompt, prompt_answer) in enumerate(zip(batch_gsm8k_ins, gsm8k_answers)):
    print(prompt, prompt_answer)
    if isinstance(prompt, list):
            pass
        else:
            prompt = [prompt]
    XXXXXXX
``` 
you would find that the prompt is not corresponding to the answers.

**Comment by yulonghui** [comment]
Hi, Shuyue
Many thanks for your reminder, we will clean the evaluation code latter.
This issue would not affect the evaluation result, but again many thanks for your reminder!
