### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by muelletm** [meta-math/MetaMath#8]
Hi!

The github README says the data license is CC by NC but the Huggingface dataset says it's Apache-2.0.

<img width="863" alt="image" src="https://github.com/meta-math/MetaMath/assets/11507045/c082ff32-88ba-4623-98eb-ab4c10f61cd8">

https://github.com/meta-math/MetaMath

https://huggingface.co/datasets/meta-math/MetaMathQA

Thanks a lot!

**Comment by yulonghui** [comment]
Hi~
muelletm, 
Many thanks for your reminder, We have updated the data protocol to the MIT License. https://huggingface.co/datasets/meta-math/MetaMathQA
This means that the wonderful MetaMathQA datasets can now be used to train a commercial model.
