### ISSUE TITLE
Ask for adding a new baseline——MuggleMATH in the Comparing MetaMath with the LLM models

### ISSUE THREAD

**Issue by ChengpengLi1003** [meta-math/MetaMath#9]
Hi,
Could you please add a new baseline——MuggleMATH in the Comparing MetaMath with the LLM models on the github webpage?
MuggleMATH mainly investigates the scaling law and generalization for data augmentation for LLM math reasoning and gets comparable results in GSM8K. The address of paper is https://arxiv.org/abs/2310.05506 . 
Thanks a lot!

**Comment by ChengpengLi1003** [comment]
Hi,
could you please add a new baseline——MuggleMATH in the Comparing MetaMath with the LLM models ?
MuggleMATH mainly investigate the scaling law and generalization for data augmentation for LLM math reasoning and gets comparable results in GSM8K. The address of paper is https://arxiv.org/abs/2310.05506 .

**Comment by yulonghui** [comment]
Hi, Chengpeng,
Thanks for your contributions of MuggleMATH to the math reasoning community.
We would add a citation of MuggleMATH in our updated version.
